### PR TITLE
gcmon-234 and gcmon-235; initial review

### PR DESCRIPTION
**Pull request by mamcderm-usgs**
Dave - this seems to be working but please review and let me know if I've missed anything.

### CODE REVIEW

**Comment by davidmsibley** [comment]
:+1:

Looks good.  Also, you're right to take out the feature toggle for CRD since we don't need it.  Could you clean up these two references while you're in there?

https://github.com/mamcderm-usgs/gcmrc-ui-parent/blob/gcmon-234/gcmrc-ui/src/main/webapp/app/gcmrc.jsp#L22
https://github.com/mamcderm-usgs/gcmrc-ui-parent/blob/gcmon-234/gcmrc-ui/src/main/webapp/app/gcmrc.jsp#L66

and since I just did a quick smoke test as well as review, I noticed Upper Limitrophe and Lower Limitrophe don't have uncertainty sliders? Data issue maybe?

**Comment by mamcderm-usgs** [comment]
I also noticed the missing sliders/data on Upper and Lower Limitrophe.  I was assuming it was a data problem since the other two reaches seemed to be working.  Is this something I should try to diagnose or should I have Megan look at that?

**Comment by mhines-usgs** [comment]
@mamcderm-usgs I can definitely take a closer look at the data. Is this safe to merge/put out on dev in the meantime? @davidmsibley

**Comment by davidmsibley** [comment]
:shipit:

**Pull request merged**
