### PR TITLE
Significantly loosened duration curve validation constraints.

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
Thanks! Pulling this locally to play a little with it!

**Comment by mhines-usgs** [comment]
Also, all I could find was an arbitrary reference to the 1000 here: https://internal.cida.usgs.gov/jira/browse/GCMON-169?focusedCommentId=97713&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-97713

**Comment by mhines-usgs** [comment]
This seems fine to me, I'm inclined to merge and put it up on dev and QA for David to look at. Thanks!!

**Comment by zmoore-usgs** [comment]
Let's go for it! :shipit:

**Pull request merged**
